# Generated by Django 3.2.9 on 2022-04-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_eng', '0002_auto_20220409_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enoldproject',
            name='about',
        ),
    ]
