# Generated by Django 3.2.9 on 2021-12-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
