# Generated by Django 3.2.9 on 2021-12-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='first_ame',
            new_name='first_name',
        ),
    ]
