# Generated by Django 3.2.9 on 2021-12-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0003_rename_first_ame_message_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project')),
                ('about', models.TextField(max_length=255, verbose_name='Description')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('project_link', models.CharField(max_length=500, verbose_name='Link')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('start', models.IntegerField(max_length=4, verbose_name='Year of start')),
                ('end', models.IntegerField(max_length=4, verbose_name='Year of end')),
            ],
        ),
    ]
