# Generated by Django 3.2.9 on 2021-12-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0005_auto_20211219_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.IntegerField(null=True, verbose_name='Year of end'),
        ),
        migrations.AlterField(
            model_name='project',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size'),
        ),
    ]
