# Generated by Django 3.2.9 on 2021-12-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0007_remove_project_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project')),
                ('about', models.TextField(max_length=255, verbose_name='Description')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('start', models.IntegerField(verbose_name='Year of start')),
                ('end', models.IntegerField(null=True, verbose_name='Year of end')),
            ],
        ),
    ]
