# Generated by Django 3.2.9 on 2021-12-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0008_oldproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
            ],
        ),
        migrations.AlterModelOptions(
            name='oldproject',
            options={'ordering': ('-end',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-end',)},
        ),
    ]
