# Generated by Django 3.2.9 on 2021-12-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0009_auto_20211219_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Surname')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('year', models.IntegerField(max_length=10, verbose_name='Year of Birth')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building_business_card.vacancy')),
            ],
        ),
    ]
