# Generated by Django 3.2.9 on 2022-01-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0012_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='newemployee',
            options={'verbose_name': 'new employee', 'verbose_name_plural': 'new employees'},
        ),
        migrations.AlterModelOptions(
            name='oldproject',
            options={'ordering': ('-end',), 'verbose_name': 'old project', 'verbose_name_plural': 'old projects'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-end',), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
    ]
