# Generated by Django 3.2.9 on 2022-02-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0013_auto_20220117_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemployee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='location',
            field=models.CharField(max_length=100, verbose_name='местоположение'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='phone',
            field=models.BigIntegerField(verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building_business_card.vacancy', verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='year',
            field=models.IntegerField(max_length=10, verbose_name='год рождения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(max_length=100, verbose_name='должность'),
        ),
    ]
