# Generated by Django 3.2.9 on 2022-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0016_auto_20220212_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallpaper',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
