# Generated by Django 3.2.9 on 2022-04-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_business_card', '0018_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newemployee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='location',
            field=models.CharField(max_length=100, verbose_name='miasto, w którym teraz jesteś'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='phone',
            field=models.BigIntegerField(verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building_business_card.vacancy', verbose_name='Dostępne stanowiska'),
        ),
        migrations.AlterField(
            model_name='newemployee',
            name='year',
            field=models.IntegerField(max_length=10, verbose_name='rok urodzenia'),
        ),
    ]
