# Generated by Django 3.2.9 on 2022-02-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.BigIntegerField(verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='RuOldProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project')),
                ('about', models.TextField(max_length=255, verbose_name='Description')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('start', models.IntegerField(verbose_name='Year of start')),
                ('end', models.IntegerField(null=True, verbose_name='Year of end')),
            ],
            options={
                'verbose_name': 'old project',
                'verbose_name_plural': 'old projects',
                'ordering': ('-end',),
            },
        ),
        migrations.CreateModel(
            name='RuProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project')),
                ('about', models.TextField(max_length=255, verbose_name='Description')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('project_link', models.CharField(max_length=500, verbose_name='Link')),
                ('start', models.IntegerField(verbose_name='Year of start')),
                ('end', models.IntegerField(null=True, verbose_name='Year of end')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('-end',),
            },
        ),
        migrations.CreateModel(
            name='RuVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='должность')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='RuNewEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('phone', models.BigIntegerField(verbose_name='телефон')),
                ('year', models.IntegerField(max_length=10, verbose_name='год рождения')),
                ('location', models.CharField(max_length=100, verbose_name='город, в котором сейчас находитесь')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building_rus.ruvacancy', verbose_name='Доступные должности')),
            ],
            options={
                'verbose_name': 'new employee',
                'verbose_name_plural': 'new employees',
            },
        ),
    ]
