# Generated by Django 3.2.9 on 2022-04-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_rus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruoldproject',
            name='about',
        ),
        migrations.AlterField(
            model_name='runewemployee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="ім'я"),
        ),
        migrations.AlterField(
            model_name='runewemployee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='прізвище'),
        ),
        migrations.AlterField(
            model_name='runewemployee',
            name='location',
            field=models.CharField(max_length=100, verbose_name='місто, в якому зараз перебуваєте'),
        ),
        migrations.AlterField(
            model_name='runewemployee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='building_rus.ruvacancy', verbose_name='Доступні вакансії'),
        ),
        migrations.AlterField(
            model_name='runewemployee',
            name='year',
            field=models.IntegerField(max_length=10, verbose_name='рік народження'),
        ),
    ]
